[package]
name = "taizen"
version = "0.1.0"
authors = ["NerdyPepper <akshayoppiliappan@gmail.com>"]
description = "TUI MediaWiki browser"

[dependencies]
reqwest = { git = "https://github.com/seanmonstar/reqwest" }
serde_json = { git = "https://github.com/serde-rs/json" }
cursive = { git = "https://github.com/gyscos/Cursive" }
regex = "1"
urlencoding = "1.0.0"
clap = "2.32.0"
lazy_static = "1.0.2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

